#include "src/game/envfx_snow.h"

const GeoLayout pss_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pss_dl_door_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, 2457, 1221, 90, 0, 90, pss_dl_gems_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pss_dl_ground_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, 0, 1000, 0, -90, 0, pss_dl_ground_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, 1512, 1221, pss_dl_platform_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 1512, 1221, pss_dl_platform_glass_mesh_layer_5),
		GEO_ROTATION_NODE_WITH_DL(LAYER_FORCE, 90, 0, 0, pss_dl_skybox1_mesh_layer_0),
		GEO_ROTATION_NODE_WITH_DL(LAYER_FORCE, 0, -36, 0, pss_dl_skybox2_mesh_layer_0),
		GEO_ROTATION_NODE_WITH_DL(LAYER_FORCE, 0, -36, 0, pss_dl_skybox3_mesh_layer_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_FORCE, 0, 9538, 0, 0, -45, 0, pss_dl_skybox4sh_mesh_layer_0),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1122, 0, 786, pss_dl_stairs_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1122, 0, 786, pss_dl_stairs2_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 17867, 0, 0, 90, 0, 90, pss_dl_sun_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 17867, 0, 0, 90, 0, 90, pss_dl_sun_001_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 17867, 0, 0, 90, 0, 90, pss_dl_sun_002_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 17867, 0, 0, 90, 0, 90, pss_dl_sun_003_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pss_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 50000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, pss_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
