extern void scroll_bits_dl_Bowser_Level_mesh_layer_1_vtx_10();
extern void scroll_bits_dl_Bowser_Level_mesh_layer_1_vtx_12();
extern void scroll_bits_dl_Bowser_Level_mesh_layer_1_vtx_14();
extern void scroll_bits_dl_Bowser_Level_mesh_layer_1_vtx_27();
extern void scroll_bits_dl_Bowser_Level_mesh_layer_1_vtx_28();
extern void scroll_bits_dl_Bowser_Level_mesh_layer_1_vtx_31();
extern void scroll_bits_dl_Bowser_Level_mesh_layer_1_vtx_37();
extern void scroll_bits_dl_Bowser_Level_001_mesh_layer_1_vtx_0();
extern void scroll_bits();
