#include "src/game/envfx_snow.h"

const GeoLayout bits_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bits_dl_Bowser_Level_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bits_dl_Bowser_Level_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bits_dl_Bowser_Level_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bits_dl_Bowser_Level_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bits_dl_Bowser_Level_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bits_dl_Bowser_Level_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bits_dl_Bowser_Level_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_FORCE, bits_dl_Icosphere_mesh_layer_0),
		GEO_DISPLAY_LIST(LAYER_FORCE, bits_dl_Icosphere_001_mesh_layer_0),
		GEO_DISPLAY_LIST(LAYER_FORCE, bits_dl_Icosphere_002_mesh_layer_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bits_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 50000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bits_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_NORMAL, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
