#include "src/game/envfx_snow.h"

const GeoLayout jrb_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -7723, 0, 6950, jrb_dl_Brimstone_Banks_Definitive_Edition_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jrb_dl_Brimstone_Banks_Definitive_Edition_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -7723, 0, 6950, 90, 0, 0, jrb_dl_Brimstone_Banks_Definitive_Edition_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -7723, 0, 6950, jrb_dl_Brimstone_Banks_Definitive_Edition_002_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -7723, 0, 6950),
		GEO_OPEN_NODE(),
			GEO_CULL(2800, 32000, 1500, 32000, -32000, -3500, 0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_Brimstone_Banks_Definitive_Edition_003_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -7723, 0, 6950),
		GEO_OPEN_NODE(),
			GEO_CULL(0, 32000, 1500, 32000, -32000, 32000, 0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_Brimstone_Banks_Definitive_Edition_004_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -7723, 0, 6950),
		GEO_OPEN_NODE(),
			GEO_CULL(-32000, 32000, -32000, 32000, 0, 32000, 0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_Brimstone_Banks_Definitive_Edition_005_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_Brimstone_Banks_Definitive_Edition_006_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -7724, 0, 6952, 90, 0, 0, jrb_dl_Brimstone_Banks_Definitive_Edition_007_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -7723, 0, 6950),
		GEO_OPEN_NODE(),
			GEO_CULL(3000, 32000, -32000, 32000, -32000, -4500, 0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, jrb_dl_Brimstone_Banks_Definitive_Edition_011_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -7723, 0, 6950, jrb_dl_Brimstone_Banks_Definitive_Edition_012_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jrb_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_FLAMING_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, jrb_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
