#include "src/game/envfx_snow.h"

const GeoLayout sa_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sa_dl_Final_Challenge_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sa_dl_Final_Challenge_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sa_dl_Final_Challenge_mesh_layer_4),
		GEO_ASM(0, geo_envfx_main),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -2286, 0, 7596),
		GEO_ASM(20480, geo_movtex_draw_water_regions),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -2286, 0, 7596),
		GEO_ASM(20481, geo_movtex_draw_water_regions),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -2286, 0, 7596),
		GEO_ASM(20482, geo_movtex_draw_water_regions),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -2286, 0, 7596),
		GEO_ASM(0, geo_cannon_circle_base),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -2286, 0, 7596),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sa_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x190B),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, sa_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
