#include "src/game/envfx_snow.h"

const GeoLayout bob_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 4256, 3412, -703, 90, 0, 77, bob_dl_aatrees_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_aflowers_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_btops_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_bwater_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -535, 1883, 2447, 90, 0, 35, bob_dl_etrees_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_fgrass_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_h_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_h_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bob_dl_h_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_lflowers_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_lflowers2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_lflowers2_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -2354, 360, -6418, bob_dl_lplat_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_lsign_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_lsign2_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1185, 223, -1073, 90, 0, 0, bob_dl_ltrees_mesh_layer_1),
		GEO_RENDER_RANGE(0, 300),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_minside_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 1260, -2985, -2123, bob_dl_nweed_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_nzbg_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bob_dl_water_texture_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
