COURSE_ACTS(COURSE_BOB, "BOUNTIFUL BASIN",	"ACROSS THE JAGGED GAP",	"SEEK THE BLUE 'SHROOM",	"HINT ART 1: THE TOAD HOUSE",	"RED COINS OF THE BASIN",	"INVESTIGATE THE WATERFALL",	"THE DEAD TREE'S TOP")

COURSE_ACTS(COURSE_WF, "TOAD TAIGA",	"CAN YOU SCALE THE MOUNTAIN?",	"A VISIT TO CITY HALL",	"RED COINS OF THE TAIGA",	"THE ELDER'S MOUNTAIN SECRET",	"SLEDDING DOWN SNOWMAN SLIDE",	"HINT ART 2: MOUNTAIN'S PEAK")

COURSE_ACTS(COURSE_JRB, "BRIMSTONE BANKS",	"HOT-FOOTED PLANK JUMP",	"TRIP DOWN THE WIRE",	"HINT ART 3: VOLCANIC RECESS",	"RED COINS OF THE BANKS",	"FIERY RACE WITH KOOPA THE QUICK",	"MARIO WINGS THROUGH THE RINGS")

COURSE_ACTS(COURSE_CCM, "DESICCATED DESERT",	"JEWEL OF THE PAVILLION",	"CLIMB THE CASTLE RUINS",	"PERILOUS PLATFORMING FOR 5 SECRETS",	"BOWSER'S DEFINITELY NOT-PACHINKO MACHINE",	"HINT ART 4: SECRET CHAMBER OF EYE'MUN'ROK",	"RED COINS OF THE CHAMBER")

COURSE_ACTS(COURSE_BBH, "BETA WORLDS",	"BONUS CONTENT",	"RIDE BIG BOO'S MERRY-GO-ROUND",	"SECRET OF THE HAUNTED BOOKS",	"SEEK THE 8 RED COINS",	"BIG BOO'S BALCONY",	"EYE TO EYE IN THE SECRET ROOM")

COURSE_ACTS(COURSE_HMC, "HAZY MAZE CAVE",	"SWIMMING BEAST IN THE CAVERN",	"ELEVATE FOR 8 RED COINS",	"METAL-HEAD MARIO CAN MOVE!",	"NAVIGATING THE TOXIC MAZE",	"A-MAZE-ING EMERGENCY EXIT",	"WATCH FOR ROLLING ROCKS")

COURSE_ACTS(COURSE_LLL, "LETHAL LAVA LAND",	"BOIL THE BIG BULLY",	"BULLY THE BULLIES",	"8-COIN PUZZLE WITH 15 PIECES",	"RED-HOT LOG ROLLING",	"HOT-FOOT-IT INTO THE VOLCANO",	"ELEVATOR TOUR IN THE VOLCANO")

COURSE_ACTS(COURSE_SSL, "SHIFTING SAND LAND",	"IN THE TALONS OF THE BIG BIRD",	"SHINING ATOP THE PYRAMID",	"INSIDE THE ANCIENT PYRAMID",	"STAND TALL ON THE FOUR PILLARS",	"FREE FLYING FOR 8 RED COINS",	"PYRAMID PUZZLE")

COURSE_ACTS(COURSE_DDD, "DIRE, DIRE DOCKS",	"BOARD BOWSER'S SUB",	"CHESTS IN THE CURRENT",	"POLE-JUMPING FOR RED COINS",	"THROUGH THE JET STREAM",	"THE MANTA RAY'S REWARD",	"COLLECT THE CAPS...")

COURSE_ACTS(COURSE_SL, "SNOWMAN'S LAND",	"SNOWMAN'S BIG HEAD",	"CHILL WITH THE BULLY",	"IN THE DEEP FREEZE",	"WHIRL FROM THE FREEZING POND",	"SHELL SHREDDIN' FOR RED COINS",	"INTO THE IGLOO")

COURSE_ACTS(COURSE_WDW, "WET-DRY WORLD",	"SHOCKING ARROW LIFTS!",	"TOP O' THE TOWN",	"SECRETS IN THE SHALLOWS & SKY",	"EXPRESS ELEVATOR--HURRY UP!",	"GO TO TOWN FOR RED COINS",	"QUICK RACE THROUGH DOWNTOWN!")

COURSE_ACTS(COURSE_TTM, "TALL, TALL MOUNTAIN",	"SCALE THE MOUNTAIN",	"MYSTERY OF THE MONKEY CAGE",	"SCARY 'SHROOMS, RED COINS",	"MYSTERIOUS MOUNTAINSIDE",	"BREATHTAKING VIEW FROM BRIDGE",	"BLAST TO THE LONELY MUSHROOM")

COURSE_ACTS(COURSE_THI, "TINY-HUGE ISLAND",	"PLUCK THE PIRANHA FLOWER",	"THE TIP TOP OF THE HUGE ISLAND",	"REMATCH WITH KOOPA THE QUICK",	"FIVE ITTY BITTY SECRETS",	"WIGGLER'S RED COINS",	"MAKE WIGGLER SQUIRM")

COURSE_ACTS(COURSE_TTC, "TICK TOCK CLOCK",	"ROLL INTO THE CAGE",	"THE PIT AND THE PENDULUMS",	"GET A HAND",	"STOMP ON THE THWOMP",	"TIMED JUMPS ON MOVING BARS",	"STOP TIME FOR RED COINS")

COURSE_ACTS(COURSE_RR, "RAINBOW RIDE",	"CRUISER CROSSING THE RAINBOW",	"THE BIG HOUSE IN THE SKY",	"COINS AMASSED IN A MAZE",	"SWINGIN' IN THE BREEZE",	"TRICKY TRIANGLES!",	"SOMEWHERE OVER THE RAINBOW")

SECRET_STAR(15, "BOWSER IN THE DARK WORLD")
SECRET_STAR(16, "BOWSER IN THE FIRE SEA")
SECRET_STAR(17, "BOWSER OVER THE RAINBOW")
SECRET_STAR(18, "THE PRINCESS'S SECRET SLIDE")
SECRET_STAR(19, "CAVERN OF THE METAL CAP")
SECRET_STAR(20, "TOWER OF THE WING CAP")
SECRET_STAR(21, "VANISH CAP UNDER THE MOAT")
SECRET_STAR(22, "WING MARIO OVER THE RAINBOW")
SECRET_STAR(23, "INSIDE THE GEM DOOR")
SECRET_STAR(24, "")
CASTLE_SECRET_STARS("CASTLE SECRET STARS")
EXTRA_TEXT(0,"ONE OF THE CASTLE'S SECRET STARS!")
EXTRA_TEXT(1,"")
EXTRA_TEXT(2,"")
EXTRA_TEXT(3,"")
EXTRA_TEXT(4,"")
EXTRA_TEXT(5,"")
EXTRA_TEXT(6,"")
