extern const GeoLayout ending_area_1_geo[];
extern const GeoLayout ending_area_1[];
extern const Collision ending_area_1_collision[];
extern const MacroObject ending_area_1_macro_objs[];
extern Lights1 ending_dl_f3dlite_material_001_lights;
extern u8 ending_dl_tfp2_rgba16[];
extern Vtx ending_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ending_dl_Plane_mesh_layer_1_vtx_0[3086];
extern Vtx ending_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx ending_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx ending_dl_Plane_mesh_layer_1[];
extern Gfx ending_dl_Plane_001_mesh_layer_1[];
