extern void scroll_jrb_dl_Brimstone_Banks_Definitive_Edition_mesh_layer_1_vtx_32();
extern void scroll_jrb_dl_skybox2_mesh_layer_0_vtx_0();
extern void scroll_gfx_mat_jrb_dl_LavaPools__noflow__001_f3d_001();
extern void scroll_gfx_mat_jrb_dl_AlsoFlowingLava_001_f3d_001();
extern void scroll_gfx_mat_jrb_dl_f3dlite_material_layer1();
extern void scroll_gfx_mat_jrb_dl_f3dlite_material_005_layer0();
extern void scroll_jrb();
