extern void scroll_bowser_3_dl_Bowser_Fight_mesh_layer_1_vtx_0();
extern void scroll_bowser_3_dl_Bowser_Fight_002_mesh_layer_1_vtx_0();
extern void scroll_bowser_3_dl_Bowser_Fight_003_mesh_layer_5_vtx_0();
extern void scroll_bowser_3_dl_skybox1_mesh_layer_0_vtx_0();
extern void scroll_bowser_3_dl_skybox2_mesh_layer_0_vtx_0();
extern void scroll_gfx_mat_bowser_3_dl__9_f3d_layer1();
extern void scroll_gfx_mat_bowser_3_dl_f3dlite_material_005_layer0();
extern void scroll_bowser_3();
